# ---- Build stage ----
FROM maven:3.9.8-eclipse-temurin-21-alpine AS build
WORKDIR /src
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests clean package

# ---- Runtime stage ----
FROM amazoncorretto:21-alpine-jdk
LABEL maintainer="Paras Verma"
WORKDIR /app
COPY --from=build /src/target/*-SNAPSHOT.jar app.jar
ENV SPRING_PROFILES_ACTIVE=prod
ENTRYPOINT ["java","-jar","/app/app.jar"]
